- name: extract backend artifacts
  unarchive:
    src: artifact.tar.gz
    dest: ~/

- name: Start backend
  shell: |
    cd ~/backend 
    npm install
    pm2 stop default
    pm2 start npm -- start
